name: Task
description: Design system task
labels: []
body:
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
  - type: textarea
    id: proposed-fix
    attributes:
      label: Proposed fix
    validations:
      required: false
  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      value: "None"
    validations:
      required: false
